// ===== 基础类型 =====
export type {
  Message,
  UserRole as CommonUserRole,
  User as CommonUser,
  AuthenticatedRequest,
  ApiResponse,
  ApiError,
  AppError,
  ResponseMeta,
  MediaFile,
  PaginationParams,
  PaginatedResponse,
  DateRange,
  SortOrder,
  Status,
  BaseEntity,
  AuditableEntity,
  Environment,
  Config,
  ValidationError,
  ValidationResult,
  JsonValue,
  JsonObject,
  JsonArray,
  JsonPrimitive,
} from './common';

// ===== 数据库类型 =====
export type {
  UUID as DatabaseUUID,
  Timestamp as DatabaseTimestamp,
  DatabaseType,
  QueryParams,
  WhereCondition,
  OrderBy,
  PaginationOptions as DatabasePaginationOptions,
  TransactionCallback,
  DatabaseError,
  DatabaseConnection,
  RedisConnection,
  HealthStatus,
  QueryResult as DatabaseQueryResult,
  DatabaseOperations,
  RedisOperations,
  UserRole as DatabaseUserRole,
  Gender,
  GrowthCategory as DatabaseGrowthCategory,
  AIRole as DatabaseAIRole,
  NotificationType as DatabaseNotificationType,
  RecommendationType as DatabaseRecommendationType,
  UploadType,
  User,
  User as DatabaseUser,
  CreateUser,
  UpdateUser,
  Child,
  CreateChild,
  UpdateChild,
  DatabaseGrowthRecord,
  CreateDatabaseGrowthRecord,
  UpdateDatabaseGrowthRecord,
  AIConversation,
  CreateAIConversation,
  AIRoleConfig as DatabaseAIRoleConfig,
  CreateAIRole,
  UpdateAIRole,
  Notification as DatabaseNotification,
  CreateNotification,
  UpdateNotification,
  Recommendation as DatabaseRecommendation,
  CreateRecommendation,
  SystemConfig,
  CreateSystemConfig,
  UpdateSystemConfig,
  FileUpload,
  CreateFileUpload,
  UserSession,
  CreateUserSession,
  AuditLog,
  CreateAuditLog,
  UserStats,
  ChildStats,
  DailyStats,
  Migration,
  MigrationStatus,
  QueryBuilder,
  Repository,
  CacheKey,
  CacheValue,
  CacheOptions,
  DatabaseConfig,
  ConnectionPool,
  DatabaseMetrics,
  QueryLog,
  DatabaseLogger,
  TransactionOptions,
  Savepoint,
  Transaction,
  IndexType,
  IndexDefinition,
  ForeignKeyAction,
  ForeignKeyDefinition,
  TriggerTiming,
  TriggerEvent,
  TriggerDefinition,
  ColumnDefinition,
  TableDefinition,
  DatabaseSchema,
  DataType,
  ColumnConstraint,
  TableConstraint,
} from './database';

// ===== 分析类型 =====
export type {
  MetricType,
  AggregationType,
  TimeGranularity,
  ChartType,
  TrendDirection,
  ComparisonType,
  AlertSeverity,
  ReportFormat,
  ExportFrequency,
  DataSource,
  Metric,
  MetricValue,
  MetricSeries,
  Dimension,
  Filter,
  QueryOptions,
  QueryResult as AnalyticsQueryResult,
  ChartConfig,
  Dashboard,
  DashboardLayout,
  Widget,
  MetricConfig,
  TableConfig,
  TextConfig,
  Report,
  Schedule as AnalyticsSchedule,
  Alert,
  AlertCondition,
  NotificationChannel,
  AlertTrigger,
  TrendAnalysis,
  AnomalyDetection,
  Forecast,
  CohortAnalysis,
  FunnelAnalysis,
  Segment,
  HeatmapData,
  SankeyData,
  TreemapData,
  HistogramData,
  ScatterData,
  SystemPerformanceMetrics,
  UserBehaviorMetrics,
  BusinessMetrics,
  GrowthMetrics,
  AssessmentMetrics,
  AnalyticsEvent,
  EventAggregation,
  RealtimeMetric,
  RealtimeDashboard,
  DataQualityReport,
  AnalyticsExport,
  AnalyticsConfig,
  ComparisonResult,
  Insight,
  AnalyticsQuery,
} from './analytics';

// ===== 交互类型 =====
export type {
  InteractionType,
  InteractionMood,
  InteractionSentiment,
  InteractionRecord,
  InteractionAnalysis,
  InteractionStats,
  InteractionFilter,
  InteractionCreateInput,
  InteractionUpdateInput,
  AIRole as InteractionAIRole,
  AIRoleConfig as InteractionAIRoleConfig,
  ConversationMessage,
  ConversationSession,
  ConversationStats,
  ConversationFilter,
  ConversationCreateInput,
  ConversationHistoryInput,
  EmotionAnalysis as InteractionEmotionAnalysis,
  EmotionTrend as InteractionEmotionTrend,
  EmotionStats,
  CommentType,
  Comment,
  CommentWithUser,
  CommentCreateInput,
  CommentUpdateInput,
  FeedbackType,
  Feedback,
  FeedbackCreateInput,
  FeedbackStats,
  NotificationType as InteractionNotificationType,
  Notification as InteractionNotification,
  NotificationCreateInput as InteractionNotificationCreateInput,
  NotificationStats,
  RatingTargetType,
  Rating,
  RatingCreateInput,
  RatingStats,
  ReactionType,
  Reaction,
  ReactionStats,
  InteractionInsight,
  InteractionDashboard,
  InteractionSearchQuery,
  InteractionSearchResult,
} from './interaction';

// ===== 情感类型 =====
export type {
  EmotionType,
  EmotionInsight,
  EmotionAnalysis,
  EmotionResult,
  EmotionPattern,
  EmotionalPattern,
  EmotionalMemory,
  EmotionTrend,
  EmotionCategory,
} from './emotion';

// ===== 成长类型 =====
export type {
  GrowthCategory as GrowthCategoryType,
  GrowthStageId,
  DevelopmentDimensionId,
  GrowthRecord,
  GrowthRecordWithAnalysis,
  GrowthRecordAnalysis,
  GrowthRecordStats,
  GrowthRecordFilter,
  GrowthRecordCreateInput,
  GrowthRecordUpdateInput,
  DevelopmentDimension,
  AgeStageConfig,
  Age,
  Milestone,
  MilestoneCreateInput,
  MilestoneUpdateInput,
  MilestoneStats,
  Assessment,
  DimensionScore,
  AssessmentCreateInput,
  AssessmentUpdateInput,
  AssessmentTrend,
  AssessmentStats,
  RecommendationType as GrowthRecommendationType,
  Recommendation as GrowthRecommendation,
  RecommendationCreateInput as GrowthRecommendationCreateInput,
  RecommendationStats as GrowthRecommendationStats,
  GrowthTimeline,
  GrowthSummary,
  GrowthInsight,
  GrowthDashboard,
  GrowthReport,
  GrowthReportChart,
  GrowthGoal,
  GrowthGoalCreateInput,
  GrowthGoalUpdateInput,
  GrowthGoalStats,
  GrowthComparison,
} from './growth';

// ===== AI 类型 =====
export type {
  AIRole,
  VoiceStyle,
  DifficultyLevel,
  QueryComplexity,
  RelevanceLevel,
  HealthStatus as AIHealthStatus,
  MessageRole,
  RoleConfig,
  KnowledgeDocument,
  KnowledgeMetadata,
  RetrievalResult,
  SearchQuery,
  SearchFilters,
  RAGContext,
  UserContext,
  RAGResponse,
  EmbeddingResult,
  ChatMessage,
  ChatOptions,
  ChatResponse,
  TokenUsage,
  ModelInfo,
  ModelDetails,
  AIHealthStatus as AIHealthStatusType,
  MemoryUsage as AIMemoryUsage,
  ResponseTimeMetrics,
  AIServicePerformanceMetrics,
  CoordinatedResponse,
  SupportingInsight,
  RoleInfo,
  QueryAnalysis,
  ChildContext,
  KnowledgeStats,
  AIRequest,
  AISession,
  AIModelConfig,
  RAGEngineConfig,
  AISystemConfig,
  OllamaConfig,
  OpenAIConfig,
  AIError,
  AIAnalytics,
  AIInsight,
  AIFeedback,
  AIRecommendation,
  AIPromptTemplate,
  AIConversationTurn,
  AIConversationSummary,
  AITrainingData,
  AIModelMetrics,
  AIAuditLog,
} from './ai';

// ===== 调度类型 =====
export type {
  Schedule,
  ScheduleType,
  RepeatPattern,
  ReminderType,
  SchedulePriority,
  ScheduleStatus,
  ScheduleFormData,
  RecurrenceRule,
  AISchedulePreferences,
  ScheduleTemplate,
  ScheduleConflict,
  ScheduleReminder,
  ScheduleAnalytics,
  ScheduleGoal,
  ScheduleEvent,
  CalendarView,
  TimeBlock,
  ScheduleSync,
  ScheduleExport,
  ScheduleImport,
  ScheduleFilter,
  ScheduleSort,
  ScheduleStatistics,
  ScheduleColor,
  GetScheduleColorFn,
  ScheduleValidation,
  ScheduleBatchOperation,
  ScheduleShare,
} from './schedule';

// ===== 知识引擎类型 =====
export type {
  KnowledgeNode,
  ActivityNode,
  RecommendationResult as KnowledgeRecommendationResult,
  RecommendationContext,
  RecommendationRequest as KnowledgeRecommendationRequest,
  RecommendationConfig as KnowledgeRecommendationConfig,
  Neo4jService,
  KnowledgeGraphStats,
} from './knowledge/common';

// ===== 预测引擎类型 =====
export type {
  PredictionData,
  DataPoint,
  PredictionResult,
  PredictionTask,
  PredictionConfig,
  ModelConstraints,
  ModelEvaluation,
  QualityMetrics as PredictionQualityMetrics,
  BiasReport,
  CalibrationResult,
  SensitiveData,
  ModelSelection,
  ModelFitAssessment,
  EnsembleEngine,
  Predictor,
  TimeSeriesEngine,
  AnomalyDetectionEngine,
  CausalInferenceEngine,
  TaskInfo as PredictionTaskInfo,
  StabilityMetrics,
  BiasVarianceTradeoff,
  ResidualAnalysis,
  TrainingResult,
  PerformanceHistory,
  DataDriftMetrics,
  UpdatedWeights,
  DriftDetection,
  PredictorConfig,
  SeasonalityAnalysis,
  ProbabilisticForecast,
  AnomalyReport,
  Anomaly,
  AnomalyExplanation,
  CausalGraph,
  CounterfactualResult,
  Intervention,
  PredictionInsights,
  StreamingPrediction,
  DataStream,
  ModelPerformanceMetrics,
  DriftAlert,
  Recommendation,
  RiskAssessment,
  KeyInsight,
} from './prediction/common';

// ===== 学习引擎类型 =====
export type {
  LearningModel,
  LearningSession,
  LearningResult,
  MetaLearningConfig,
  LearningTask as MetaLearningTask,
  LearningEvent,
  LearningMetrics,
  LearningHistory,
} from './learning/common';

// ===== 编排器类型 =====
export type {
  ServiceDefinition,
  ServiceStatus,
  ServiceInstance,
  GatewayConfig,
  AuthenticationConfig,
  RateLimitConfig,
  CircuitBreakerConfig,
  LoggingConfig,
  Route,
  RetryPolicy,
  OrchestrationTask,
  OrchestrationStep,
  OrchestrationResult,
  ServiceHealthCheck,
} from './orchestrator/common';

// ===== UI 类型 =====
export type {
  Badge,
  BadgeSeries,
  BadgeLevel,
  BadgeCategory,
  BadgeRarity,
  UnlockCondition,
  ConditionType,
  ShareContent,
  BadgeMetadata,
  SeriesProgress,
  SeriesMilestone,
  BadgeReward,
  BadgeGroup,
  BadgeStats,
  BadgeService,
} from './ui';

// ===== 作业类型 =====
export type {
  Homework,
  HomeworkStatus,
  HomeworkResult,
  VoiceRecording,
  HomeworkSubmission,
  HomeworkFeedback,
  HomeworkStats,
} from './homework';

// ===== 用户类型（源自 yyc3-xy-01，供 profile 页面使用） =====
export type {
  UserPreferences,
  UserProfile,
  AgeGroup,
} from './user';

// ===== 全局工具类型 =====
export interface MockChild {
  id: string;
  name: string;
  age: number;
  gender: 'male' | 'female';
  avatar?: string;
  createdAt: Date;
}

export type FilterType = 
  | 'all'
  | 'story'
  | 'memory'
  | 'slideshow'
  | 'image-to-video'
  | 'story-animation'
  | 'memory-recap';

export interface MultimodalInput {
  text?: string;
  image?: string;
  audio?: string;
  video?: string;
  metadata?: Record<string, unknown>;
}
